# Generated by Django 4.2.8 on 2023-12-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="middle_name",
        ),
        migrations.AddField(
            model_name="user",
            name="staff_id",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
