# Generated by Django 4.2.8 on 2023-12-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_remove_user_is_verified_remove_user_middle_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="allergies",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="blood_group",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="diagnosis",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="medications",
            field=models.TextField(blank=True),
        ),
    ]
