# Generated by Django 4.2.8 on 2023-12-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_rename_allergies_profile_allerg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="dob",
            field=models.DateField(blank=True, help_text="Date of birth", null=True),
        ),
    ]
