# Generated by Django 4.2.8 on 2023-12-16 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_profile_dob"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="allerg",
            new_name="allergy",
        ),
    ]
