# Generated by Django 4.2.8 on 2023-12-16 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_rename_allerg_profile_allergy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="allergy",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="blood_group",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="bmi",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="diagnosis",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="medication",
        ),
    ]
