# Generated by Django 4.2.8 on 2023-12-16 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_remove_profile_allergy_remove_profile_blood_group_and_more"),
        ("record", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicaldata",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_profile",
                to="account.profile",
            ),
            preserve_default=False,
        ),
    ]
