# Generated by Django 4.2.8 on 2023-12-16 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_remove_profile_allergy_remove_profile_blood_group_and_more"),
        ("record", "0002_medicaldata_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicaldata",
            name="profile",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_profile",
                to="account.profile",
            ),
        ),
    ]
